export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  LEAVE_REQUEST: '/leave-request',
  LEAVE_REQUEST_NEW: '/leave-request/new',
  LEAVE_REQUEST_DETAIL: '/leave-request/:id',
  APPROVALS: '/approvals',
  APPROVAL_DETAIL: '/approvals/:id',
  HISTORY: '/history',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  NOTIFICATIONS: '/notifications',
  UNAUTHORIZED: '/unauthorized',
  NOT_FOUND: '*',
} as const
