export const ROUTES = {
  LOGIN: "/login",

  EMPLOYEE_DASHBOARD: "/dashboard",
  MANAGER_DASHBOARD: "/dashboard/manager",
  HR_DASHBOARD: "/dashboard/hr",
  DIRECTOR_DASHBOARD: "/dashboard/director",
  ADMIN_DASHBOARD: "/dashboard/admin",

  APPLY_LEAVE: "/leave/apply",
  LEAVE_HISTORY: "/leave/history",
  LEAVE_DETAILS: "/leave/:id",

  PENDING_APPROVALS: "/approvals",
  MANAGER_APPROVAL: "/approvals/manager",
  HR_APPROVAL: "/approvals/hr",
  DIRECTOR_APPROVAL: "/approvals/director",

  ADMIN_USERS: "/admin/users",
  ADMIN_USER_DETAILS: "/admin/users/:id",
  ADMIN_CREATE_USER: "/admin/users/create",
  ADMIN_EDIT_USER: "/admin/users/:id/edit",
  ADMIN_DEPARTMENTS: "/admin/departments",
  ADMIN_LEAVE_TYPES: "/admin/leave-types",
  ADMIN_APPROVAL_MATRIX: "/admin/approval-matrix",
  ADMIN_LEAVE_REQUESTS: "/admin/leave-requests",
  ADMIN_REPORTS: "/admin/reports",

  NOTIFICATIONS: "/notifications",
  PROFILE: "/profile",
  SETTINGS: "/settings",

  UNAUTHORIZED: "/unauthorized",
  NOT_FOUND: "*",
};

export const ROUTE_LABELS = {
  [ROUTES.LOGIN]: "Login",
  [ROUTES.EMPLOYEE_DASHBOARD]: "Dashboard",
  [ROUTES.MANAGER_DASHBOARD]: "Manager Dashboard",
  [ROUTES.HR_DASHBOARD]: "HR Dashboard",
  [ROUTES.DIRECTOR_DASHBOARD]: "Director Dashboard",
  [ROUTES.ADMIN_DASHBOARD]: "Admin Dashboard",
  [ROUTES.APPLY_LEAVE]: "Apply Leave",
  [ROUTES.LEAVE_HISTORY]: "Leave History",
  [ROUTES.LEAVE_DETAILS]: "Leave Details",
  [ROUTES.PENDING_APPROVALS]: "Pending Approvals",
  [ROUTES.MANAGER_APPROVAL]: "Manager Approvals",
  [ROUTES.HR_APPROVAL]: "HR Approvals",
  [ROUTES.DIRECTOR_APPROVAL]: "Director Approvals",
  [ROUTES.ADMIN_USERS]: "Users",
  [ROUTES.ADMIN_USER_DETAILS]: "User Details",
  [ROUTES.ADMIN_CREATE_USER]: "Create User",
  [ROUTES.ADMIN_EDIT_USER]: "Edit User",
  [ROUTES.ADMIN_DEPARTMENTS]: "Departments",
  [ROUTES.ADMIN_LEAVE_TYPES]: "Leave Types",
  [ROUTES.ADMIN_APPROVAL_MATRIX]: "Approval Matrix",
  [ROUTES.ADMIN_LEAVE_REQUESTS]: "Leave Requests",
  [ROUTES.ADMIN_REPORTS]: "Reports",
  [ROUTES.NOTIFICATIONS]: "Notifications",
  [ROUTES.PROFILE]: "Profile",
  [ROUTES.SETTINGS]: "Settings",
  [ROUTES.UNAUTHORIZED]: "Unauthorized",
  [ROUTES.NOT_FOUND]: "Not Found",
};
