import { Role } from '@/types/user.types'

export const ROLE_PERMISSIONS: Record<Role, string[]> = {
  EMPLOYEE: [
    'leave:create',
    'leave:read:own',
    'leave:cancel:own',
    'profile:read',
    'profile:update',
  ],
  MANAGER: [
    'leave:create',
    'leave:read:own',
    'leave:read:team',
    'leave:cancel:own',
    'approval:read',
    'approval:approve',
    'approval:reject',
    'profile:read',
    'profile:update',
  ],
  HR: [
    'leave:create',
    'leave:read:own',
    'leave:read:all',
    'leave:cancel:own',
    'approval:read',
    'approval:approve',
    'approval:reject',
    'profile:read',
    'profile:update',
    'reports:read',
  ],
  ADMIN: [
    'leave:create',
    'leave:read:own',
    'leave:read:all',
    'leave:cancel:own',
    'approval:read',
    'approval:approve',
    'approval:reject',
    'profile:read',
    'profile:update',
    'reports:read',
    'users:manage',
    'settings:manage',
  ],
}
